# File Name: zshenv
# File Path: /etc/zsh/zshenv
# Description: System wide zsh environment configuration file.

# Copyright (c) 2024 Ray Adams
# SPDX-License-Identifier: BSD-3-Clause

# Version 1.0.0

export ZDOTDIR="$HOME/.config/zsh"
